on:
  release:
    types: [created]
  workflow_dispatch:

name: Build Release Linux
jobs:
  bls-c2w-images:
    strategy:
      matrix:
        include:
          - build: ubuntu-20.04
            os: ubuntu-20.04
            rust: stable
            runson: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            arch: x86_64
            cross: false
          - build: linux_arm64
            os: linux-latest
            runson: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-gnu
            arch: aarch64
            cross: false
    runs-on: ${{ matrix.runson }}
    steps:
      - uses: actions/checkout@v2
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Edit Toml
        uses: dmikey/toml-editor@master
        with:
          file: "script/inc.mk"
          key: "IMAGE_TAG_VERSION"
          value: "${{ steps.get_release.outputs.tag_name }}"
      - name: build
        run: |
          cd script
          make
      - name: Login to Docker Hub
        run: |
          echo "${{secrets.GITHUB_TOKEN}}"|docker login ghcr.io -u ${{github.actor}} --password-stdin
      - name: push
        run: |
          cd script
          make push
      
      
    
