on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Build Release Linux
jobs:
  bls-c2w-images:
    strategy:
      matrix:
        include:
          - build: ubuntu-20.04
            os: ubuntu-20.04
            rust: stable
            runson: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            arch: x86_64
            cross: false
          - build: linux_arm64
            os: linux-latest
            runson: ubuntu-latest
            rust: stable
            target: aarch64-unknown-linux-gnu
            arch: aarch64
            cross: false
    runs-on: ${{ matrix.runson }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: |
          cd script
          make
      - name: push
        run: |
          cd script
          make push
      
    
        
